FROM python:3.9-slim

WORKDIR /app

# Cài đặt dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    ffmpeg \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Cài đặt Python packages
COPY requirements-worker.txt .
RUN pip install --no-cache-dir -r requirements-worker.txt

# Copy source code
COPY worker.py .
COPY utils/ ./utils/

# Tạo thư mục cho file tạm
RUN mkdir -p /app/temp_files && chmod 777 /app/temp_files

# Khởi động worker
CMD ["python", "worker.py"]